add_library(gr-digital INTERFACE)
add_library(gnuradio4::gr-digital ALIAS gr-digital)
target_link_libraries(gr-digital INTERFACE gnuradio4::gnuradio-core gnuradio4::gnuradio-algorithm)
target_include_directories(gr-digital INTERFACE $<BUILD_INTERFACE:${CMAKE_CURRENT_SOURCE_DIR}/include/>
                                                $<INSTALL_INTERFACE:include/>)
install(TARGETS gr-digital EXPORT gnuradio4Targets)
install(DIRECTORY "${CMAKE_CURRENT_SOURCE_DIR}/include/gnuradio-4.0/digital"
        DESTINATION "${CMAKE_INSTALL_INCLUDEDIR}/gnuradio-4.0")

gr_add_block_library(
  GrDigitalBlocks
  MAKE_SHARED_LIBRARY
  ${GR4_BLOCK_STATIC_LIBRARY}
  HEADERS
  include/gnuradio-4.0/digital/AccessCodeCorrelator.hpp
  include/gnuradio-4.0/digital/BitPacking.hpp
  include/gnuradio-4.0/digital/ConstellationBlocks.hpp
  include/gnuradio-4.0/digital/CpmModulate.hpp
  include/gnuradio-4.0/digital/CrcBlocks.hpp
  include/gnuradio-4.0/digital/DelimiterExtractor.hpp
  include/gnuradio-4.0/digital/DelimiterFramer.hpp
  include/gnuradio-4.0/digital/DifferentialCoding.hpp
  include/gnuradio-4.0/digital/LengthHeaderFramer.hpp
  include/gnuradio-4.0/digital/LinearEqualizer.hpp
  include/gnuradio-4.0/digital/Manchester.hpp
  include/gnuradio-4.0/digital/ManchesterCombine.hpp
  include/gnuradio-4.0/digital/OffsetWordFraming.hpp
  include/gnuradio-4.0/digital/PacketFramer.hpp
  include/gnuradio-4.0/digital/PamSymbols.hpp
  include/gnuradio-4.0/digital/PreambleCorrelator.hpp
  include/gnuradio-4.0/digital/Scrambler.hpp
  include/gnuradio-4.0/digital/SignalQuality.hpp
  LINK_LIBRARIES
  gr-digital)

if(TARGET gnuradio4::GrDigitalBlocksShared AND ENABLE_TESTING)
  add_subdirectory(test)
endif()

add_subdirectory(bench)
