#include <boost/ut.hpp>

#include <algorithm>
#include <array>
#include <atomic>
#include <bit>
#include <chrono>
#include <cstddef>
#include <cstdint>
#include <span>
#include <string>
#include <string_view>
#include <thread>
#include <tuple>
#include <vector>

#include <gnuradio-4.0/Graph.hpp>
#include <gnuradio-4.0/Scheduler.hpp>

#include <gnuradio-4.0/algorithm/fec/ReedSolomon.hpp>
#include <gnuradio-4.0/fec/FecBlocks.hpp>
#include <gnuradio-4.0/fec/RsBlocks.hpp>

/*
 * The adapters are exercised through the scheduler rather than by calling them directly, because
 * what they promise is a record contract: one record in, one record out, in order, with the
 * codes' verdict accumulating in metadata and a misaligned record counted rather than absorbed.
 *
 * The kernels' own correctness is established beside them and is not restated here. What these
 * tests pin is the layer this module owns: the item-to-word mapping, the arithmetic that turns a
 * record's length into a codeword count, the metadata vocabulary, and the counters.
 */
namespace {

using gr::blocks::fec::FecDecode;
using gr::blocks::fec::FecEncode;
using gr::blocks::fec::RsDecode;
using gr::blocks::fec::RsEncode;

using Record = gr::DataSet<std::uint8_t>;

//! One binary form, with the dimensions and the correcting radius the tests read.
struct Form {
    const char* code;
    std::size_t n;       //!< bits in a codeword
    std::size_t k;       //!< information bits a codeword carries
    unsigned    t;       //!< bit errors the form corrects
    bool        refuses; //!< whether the form can report a failure at all
};

/*
 * The perfect forms cannot say no: every syndrome of Golay(23,12,7) and of Hamming(15,11,3)
 * names an error pattern inside the radius, so a word past it decodes to a neighboring codeword
 * and is reported valid. That is the kernels' documented contract, and the past-radius test
 * asserts the consequence for them rather than a refusal they cannot make.
 */
constexpr std::array<Form, 6UZ> kForms{{
    {"golay24", 24UZ, 12UZ, 3U, true},
    {"golay23", 23UZ, 12UZ, 3U, false},
    {"golay18", 18UZ, 6UZ, 3U, true},
    {"hamming15", 15UZ, 11UZ, 1U, false},
    {"hamming10", 10UZ, 6UZ, 1U, true},
    {"bch63", 63UZ, 16UZ, 11U, true},
}};

//! One known codeword per form and the information it carries, from the values the kernels' own
//! tests pin against an independent source. Golay(18,6,8) shares the extended code's codeword for
//! the same six-bit information word, and the BCH generator polynomial is by construction the
//! codeword of information word one.
struct Anchor {
    const char*   code;
    std::uint64_t codeword;
    std::uint64_t info;
};

constexpr std::array<Anchor, 6UZ> kAnchors{{
    {"golay24", 0x0018EBULL, 0x001ULL},
    {"golay23", 0x000C75ULL, 0x001ULL},
    {"golay18", 0x0018EBULL, 0x01ULL},
    {"hamming15", 0x0013ULL, 0x001ULL},
    {"hamming10", 0x001CULL, 0x01ULL},
    {"bch63", 0xCD930BDD3B2BULL, 0x0001ULL},
}};

std::uint64_t rng = 0x9E3779B97F4A7C15ULL;

[[nodiscard]] std::uint64_t next() {
    rng = rng * 6364136223846793005ULL + 1442695040888963407ULL;
    return rng >> 17U;
}

//! Every codeword of the length-15 cyclic code generated by @p generator, built here by multiplying each of the
//! 2^k information polynomials by the generator over GF(2). The code is the same set of words a systematic encoder
//! produces, and building it from the generator rather than from the kernel is what makes the past-radius
//! expectation below independent of the thing it is checking.
[[nodiscard]] std::vector<std::uint16_t> bch15Codewords(std::uint16_t generator, std::size_t k) {
    std::vector<std::uint16_t> words;
    words.reserve(1UZ << k);
    for (std::uint32_t info = 0U; info < (1U << k); ++info) {
        std::uint32_t product = 0U;
        for (std::size_t bit = 0UZ; bit < k; ++bit) {
            if (((info >> bit) & 1U) != 0U) {
                product ^= static_cast<std::uint32_t>(generator) << bit;
            }
        }
        words.push_back(static_cast<std::uint16_t>(product));
    }
    return words;
}

//! Whether any word of @p words lies within @p t bits of @p word, which is the nearest-codeword decoder's whole
//! question: no two codewords are closer than 2t + 1, so at most one can be that close.
[[nodiscard]] bool withinRadius(const std::vector<std::uint16_t>& words, std::uint16_t word, unsigned t) {
    return std::ranges::any_of(words, [word, t](std::uint16_t candidate) { return static_cast<unsigned>(std::popcount(static_cast<unsigned>(candidate ^ word))) <= t; });
}

//! The low @p count bits of @p word as items, the most significant bit first.
[[nodiscard]] std::vector<std::uint8_t> bitsOf(std::uint64_t word, std::size_t count) {
    std::vector<std::uint8_t> items(count);
    for (std::size_t i = 0UZ; i < count; ++i) {
        items[i] = static_cast<std::uint8_t>((word >> (count - 1UZ - i)) & 1ULL);
    }
    return items;
}

//! A record of @p values, shaped as the record producers in this tree shape one.
[[nodiscard]] Record record(std::vector<std::uint8_t> values, gr::property_map meta = {}) {
    Record r;
    r.signal_values = std::move(values);
    r.extents.push_back(static_cast<std::int32_t>(r.signal_values.size()));
    r.signal_names.emplace_back("fec");
    r.timing_events.resize(1UZ);
    if (!meta.empty()) {
        r.meta_information.push_back(std::move(meta));
    }
    return r;
}

//! @p count seeded random bits.
[[nodiscard]] std::vector<std::uint8_t> randomBits(std::size_t count) {
    std::vector<std::uint8_t> bits(count);
    for (std::size_t i = 0UZ; i < count; ++i) {
        bits[i] = static_cast<std::uint8_t>(next() & 1ULL);
    }
    return bits;
}

//! @p count seeded random symbols of GF(64).
[[nodiscard]] std::vector<std::uint8_t> randomSymbols(std::size_t count) {
    std::vector<std::uint8_t> symbols(count);
    for (std::size_t i = 0UZ; i < count; ++i) {
        symbols[i] = static_cast<std::uint8_t>(next() & 0x3FULL);
    }
    return symbols;
}

//! A record's count under @p key, with the key's absence reported rather than defaulted away.
[[nodiscard]] gr::Size_t metaCount(const Record& r, const char* key) {
    boost::ut::expect(!r.meta_information.empty()) << "the record carries a metadata map";
    if (r.meta_information.empty()) {
        return 0U;
    }
    const auto& map   = r.meta_information[0UZ];
    const auto  entry = map.find(gr::property_map::key_type(key));
    boost::ut::expect(entry != map.end()) << key;
    return entry == map.end() ? 0U : entry->second.value_or(gr::Size_t{0U});
}

struct RecordSource : gr::Block<RecordSource> {
    gr::PortOut<Record, gr::Async> out;
    GR_MAKE_REFLECTABLE(RecordSource, out);
    std::vector<Record>            _records;
    std::size_t                    _pos{0UZ};
    [[nodiscard]] gr::work::Status processBulk(gr::OutputSpanLike auto& outSpan) {
        const std::size_t n = std::min(outSpan.size(), _records.size() - _pos);
        for (std::size_t i = 0UZ; i < n; ++i) {
            outSpan[i] = _records[_pos + i];
        }
        outSpan.publish(n);
        _pos += n;
        return _pos == _records.size() ? gr::work::Status::DONE : gr::work::Status::OK;
    }
};

struct RecordSink : gr::Block<RecordSink> {
    gr::PortIn<Record, gr::Async> in;
    GR_MAKE_REFLECTABLE(RecordSink, in);
    std::vector<Record>            _records;
    [[nodiscard]] gr::work::Status processBulk(gr::InputSpanLike auto& inSpan) {
        for (const auto& r : inSpan) {
            _records.push_back(r);
        }
        std::ignore = inSpan.consume(inSpan.size());
        return gr::work::Status::OK;
    }
};

//! Flips the bits at fixed item positions of every record passing through, so the damage a chain
//! sees is the same on every run and on every schedule.
struct BitFlipper : gr::Block<BitFlipper> {
    gr::PortIn<Record, gr::Async>  in;
    gr::PortOut<Record, gr::Async> out;
    GR_MAKE_REFLECTABLE(BitFlipper, in, out);
    std::vector<std::size_t>       _positions;
    [[nodiscard]] gr::work::Status processBulk(gr::InputSpanLike auto& inSpan, gr::OutputSpanLike auto& outSpan) {
        const std::size_t n = std::min(inSpan.size(), outSpan.size());
        for (std::size_t i = 0UZ; i < n; ++i) {
            Record damaged = inSpan[i];
            for (const std::size_t p : _positions) {
                if (p < damaged.signal_values.size()) {
                    damaged.signal_values[p] = static_cast<std::uint8_t>(damaged.signal_values[p] ^ 1U);
                }
            }
            outSpan[i] = std::move(damaged);
        }
        std::ignore = inSpan.consume(n);
        outSpan.publish(n);
        return n == 0UZ ? gr::work::Status::INSUFFICIENT_INPUT_ITEMS : gr::work::Status::OK;
    }
};

//! Run @p flow to completion under the simple scheduler, then call @p after while its blocks are
//! still alive. A run that has not finished inside the timeout is stopped and reported.
template<typename After>
void runFlow(gr::Graph&& flow, After&& after) {
    gr::scheduler::Simple<> scheduler;
    boost::ut::expect(scheduler.exchange(std::move(flow)).has_value());
    std::atomic<bool> done{false};
    std::thread       runner([&scheduler, &done] {
        std::ignore = scheduler.runAndWait();
        done        = true;
    });
    const auto        start = std::chrono::steady_clock::now();
    while (!done.load() && std::chrono::steady_clock::now() - start < std::chrono::seconds(30)) {
        std::this_thread::sleep_for(std::chrono::milliseconds(10));
    }
    if (!done.load()) {
        scheduler.requestStop();
    }
    runner.join();
    boost::ut::expect(done.load());
    after();
}

//! Run @p records through one block configured by @p settings, handing the block to @p inspect
//! before the graph is torn down.
template<typename TBlock, typename Inspect>
[[nodiscard]] std::vector<Record> runBlock(gr::property_map settings, std::vector<Record> records, Inspect&& inspect) {
    gr::Graph flow;
    auto&     src = flow.emplaceBlock<RecordSource>();
    src._records  = std::move(records);
    auto& coder   = flow.emplaceBlock<TBlock>(std::move(settings));
    auto& sink    = flow.emplaceBlock<RecordSink>();
    boost::ut::expect(flow.connect<"out", "in">(src, coder).has_value());
    boost::ut::expect(flow.connect<"out", "in">(coder, sink).has_value());

    std::vector<Record> published;
    runFlow(std::move(flow), [&] {
        inspect(coder);
        published = std::move(sink._records);
    });
    return published;
}

template<typename TBlock>
[[nodiscard]] std::vector<Record> runBlock(gr::property_map settings, std::vector<Record> records) {
    return runBlock<TBlock>(std::move(settings), std::move(records), [](const TBlock&) {});
}

//! Encode @p info under @p code and hand back the single record of codewords it becomes.
[[nodiscard]] Record encoded(const char* code, const std::vector<std::uint8_t>& info) {
    std::vector<Record> out = runBlock<FecEncode>({{"code", std::string(code)}}, {record(info)});
    boost::ut::expect(boost::ut::eq(out.size(), 1UZ)) << code;
    return out.empty() ? Record{} : out[0UZ];
}

//! The item positions carrying @p count injected errors in the codeword starting at @p base. The
//! stride keeps them distinct and inside the shortest codeword any form uses.
[[nodiscard]] std::vector<std::size_t> errorPositions(std::size_t base, unsigned count) {
    std::vector<std::size_t> positions;
    positions.reserve(count);
    for (unsigned i = 0U; i < count; ++i) {
        positions.push_back(base + 1UZ + 3UZ * i);
    }
    return positions;
}

//! Flip the bits at @p positions of @p r.
void flipBits(Record& r, const std::vector<std::size_t>& positions) {
    for (const std::size_t p : positions) {
        boost::ut::expect(p < r.signal_values.size());
        if (p < r.signal_values.size()) {
            r.signal_values[p] = static_cast<std::uint8_t>(r.signal_values[p] ^ 1U);
        }
    }
}

//! Damage @p count symbols of @p r, starting at @p base, by a value the field cannot cancel.
void damageSymbols(Record& r, std::size_t base, unsigned count) {
    for (unsigned i = 0U; i < count; ++i) {
        const std::size_t p = base + 1UZ + 3UZ * i;
        boost::ut::expect(p < r.signal_values.size());
        if (p < r.signal_values.size()) {
            r.signal_values[p] = static_cast<std::uint8_t>((r.signal_values[p] ^ 0x15U) & 0x3FU);
        }
    }
}

template<typename TBlock>
[[nodiscard]] TBlock make(gr::property_map settings) {
    TBlock block(std::move(settings));
    block.settings().init();
    std::ignore = block.settings().applyStagedParameters();
    return block;
}

} // namespace

int main() {
    using namespace boost::ut;

    "the code and root settings are required and are checked before anything runs"_test = [] {
        expect(throws([] { std::ignore = make<FecEncode>({{"code", std::string("")}}); })) << "there is no default code";
        expect(throws([] { std::ignore = make<FecDecode>({{"code", std::string("golay25")}}); })) << "a spelling outside the six is refused";
        expect(throws([] { std::ignore = make<RsEncode>({{"roots", gr::Size_t{10U}}}); })) << "only the validated root counts are accepted";
        expect(throws([] { std::ignore = make<RsDecode>({{"roots", gr::Size_t{16U}}, {"pad", gr::Size_t{47U}}}); })) << "a shortening that leaves no information is refused";
        expect(nothrow([] { std::ignore = make<RsDecode>({{"roots", gr::Size_t{16U}}, {"pad", gr::Size_t{46U}}}); })) << "the last shortening that leaves one symbol is accepted";
    };

    // Criterion 1: seeded random information through encode and decode reproduces itself, and the
    // decode reports a clean record as clean.
    "a round trip through each binary form reproduces the information exactly"_test = [] {
        for (const Form& form : kForms) {
            const std::vector<std::uint8_t> info  = randomBits(4UZ * form.k);
            const Record                    coded = encoded(form.code, info);
            expect(eq(coded.signal_values.size(), 4UZ * form.n)) << form.code;

            std::uint64_t codewords = 0ULL;
            const auto    out       = runBlock<FecDecode>({{"code", std::string(form.code)}}, {coded}, [&codewords](const FecDecode& block) {
                codewords = block.nCodewords;
                expect(eq(block.nCorrectedErrors, std::uint64_t{0ULL}));
                expect(eq(block.nUncorrectableCodewords, std::uint64_t{0ULL}));
            });
            expect(eq(out.size(), 1UZ)) << form.code;
            expect(eq(codewords, std::uint64_t{4ULL})) << form.code;
            if (out.size() != 1UZ) {
                continue;
            }
            expect(std::ranges::equal(out[0UZ].signal_values, info)) << form.code;
            expect(eq(metaCount(out[0UZ], "corrected_errors"), gr::Size_t{0U})) << form.code;
            expect(eq(metaCount(out[0UZ], "uncorrectable_errors"), gr::Size_t{0U})) << form.code;
        }
    };

    "a round trip through each Reed-Solomon code reproduces the symbols exactly"_test = [] {
        for (const gr::Size_t roots : {gr::Size_t{8U}, gr::Size_t{12U}, gr::Size_t{16U}}) {
            const std::size_t               info    = 63UZ - static_cast<std::size_t>(roots);
            const std::vector<std::uint8_t> symbols = randomSymbols(2UZ * info);

            const auto coded = runBlock<RsEncode>({{"roots", roots}}, {record(symbols)});
            expect(eq(coded.size(), 1UZ));
            if (coded.size() != 1UZ) {
                continue;
            }
            expect(eq(coded[0UZ].signal_values.size(), 2UZ * 63UZ));

            const auto out = runBlock<RsDecode>({{"roots", roots}}, {coded[0UZ]}, [](const RsDecode& block) {
                expect(eq(block.nCorrectedErrors, std::uint64_t{0ULL}));
                expect(eq(block.nUncorrectableCodewords, std::uint64_t{0ULL}));
                expect(eq(block.nPadCorrupted, std::uint64_t{0ULL}));
            });
            expect(eq(out.size(), 1UZ));
            if (out.size() == 1UZ) {
                expect(std::ranges::equal(out[0UZ].signal_values, symbols));
                expect(eq(metaCount(out[0UZ], "corrected_errors"), gr::Size_t{0U}));
                expect(eq(metaCount(out[0UZ], "uncorrectable_errors"), gr::Size_t{0U}));
            }
        }
    };

    // Criterion 2: inside the radius the information comes back and the reported count is the
    // count injected, per codeword and summed over the record.
    "errors inside each form's radius are corrected and counted exactly"_test = [] {
        for (const Form& form : kForms) {
            const std::vector<std::uint8_t> info  = randomBits(3UZ * form.k);
            Record                          coded = encoded(form.code, info);
            for (std::size_t w = 0UZ; w < 3UZ; ++w) {
                flipBits(coded, errorPositions(w * form.n, form.t));
            }

            const gr::Size_t injected = 3U * form.t;
            const auto       out      = runBlock<FecDecode>({{"code", std::string(form.code)}}, {coded}, [injected](const FecDecode& block) {
                expect(eq(block.nCorrectedErrors, static_cast<std::uint64_t>(injected)));
                expect(eq(block.nUncorrectableCodewords, std::uint64_t{0ULL}));
            });
            expect(eq(out.size(), 1UZ)) << form.code;
            if (out.size() != 1UZ) {
                continue;
            }
            expect(std::ranges::equal(out[0UZ].signal_values, info)) << form.code;
            expect(eq(metaCount(out[0UZ], "corrected_errors"), injected)) << form.code;
            expect(eq(metaCount(out[0UZ], "uncorrectable_errors"), gr::Size_t{0U})) << form.code;
        }
    };

    "symbol errors inside each Reed-Solomon code's radius are corrected and counted exactly"_test = [] {
        for (const gr::Size_t roots : {gr::Size_t{8U}, gr::Size_t{12U}, gr::Size_t{16U}}) {
            const std::size_t               info    = 63UZ - static_cast<std::size_t>(roots);
            const unsigned                  t       = roots / 2U;
            const std::vector<std::uint8_t> symbols = randomSymbols(2UZ * info);

            auto coded = runBlock<RsEncode>({{"roots", roots}}, {record(symbols)});
            expect(eq(coded.size(), 1UZ));
            if (coded.size() != 1UZ) {
                continue;
            }
            damageSymbols(coded[0UZ], 0UZ, t);
            damageSymbols(coded[0UZ], 63UZ, t);

            const gr::Size_t injected = 2U * t;
            const auto       out      = runBlock<RsDecode>({{"roots", roots}}, {coded[0UZ]}, [injected](const RsDecode& block) {
                expect(eq(block.nCorrectedErrors, static_cast<std::uint64_t>(injected)));
                expect(eq(block.nUncorrectableCodewords, std::uint64_t{0ULL}));
            });
            expect(eq(out.size(), 1UZ));
            if (out.size() == 1UZ) {
                expect(std::ranges::equal(out[0UZ].signal_values, symbols));
                expect(eq(metaCount(out[0UZ], "corrected_errors"), injected));
            }
        }
    };

    // Criterion 3: past the radius the record still publishes and the graph continues; the forms
    // that carry a failure signal count the codeword, and the perfect forms cannot.
    "a codeword past its form's radius is counted where the form can say so, and always published"_test = [] {
        for (const Form& form : kForms) {
            const std::vector<std::uint8_t> info  = randomBits(2UZ * form.k);
            Record                          coded = encoded(form.code, info);
            // Hamming(10,6,3)'s refusal lives in five syndromes rather than in a distance, so its
            // past-radius word is the one two of its parity bits produce.
            if (std::string_view(form.code) == "hamming10") {
                flipBits(coded, {7UZ, 9UZ});
            } else {
                flipBits(coded, errorPositions(0UZ, form.t + 1U));
            }

            const gr::Size_t expected = form.refuses ? gr::Size_t{1U} : gr::Size_t{0U};
            const auto       out      = runBlock<FecDecode>({{"code", std::string(form.code)}}, {coded}, [expected](const FecDecode& block) {
                expect(eq(block.nUncorrectableCodewords, static_cast<std::uint64_t>(expected)));
                expect(eq(block.nRecords, std::uint64_t{1ULL}));
            });
            expect(eq(out.size(), 1UZ)) << form.code;
            if (out.size() != 1UZ) {
                continue;
            }
            expect(eq(out[0UZ].signal_values.size(), 2UZ * form.k)) << "the information bits ride whatever the verdict was";
            expect(eq(metaCount(out[0UZ], "uncorrectable_errors"), expected)) << form.code;
        }
    };

    "a Reed-Solomon codeword past the correction limit is counted and published"_test = [] {
        const std::size_t               info    = 63UZ - 8UZ;
        const std::vector<std::uint8_t> symbols = randomSymbols(info);

        auto coded = runBlock<RsEncode>({{"roots", gr::Size_t{8U}}}, {record(symbols)});
        expect(eq(coded.size(), 1UZ));
        if (coded.size() != 1UZ) {
            return;
        }
        damageSymbols(coded[0UZ], 0UZ, 5U); // one past the four symbols the code corrects

        const auto out = runBlock<RsDecode>({{"roots", gr::Size_t{8U}}}, {coded[0UZ]}, [](const RsDecode& block) {
            expect(eq(block.nUncorrectableCodewords, std::uint64_t{1ULL}));
            expect(eq(block.nRecords, std::uint64_t{1ULL}));
        });
        expect(eq(out.size(), 1UZ));
        if (out.size() == 1UZ) {
            expect(eq(out[0UZ].signal_values.size(), info));
            expect(eq(metaCount(out[0UZ], "uncorrectable_errors"), gr::Size_t{1U}));
        }
    };

    // Criterion 4: the item-to-word mapping against values this tree did not compute.
    "each form's known codeword maps onto items in transmitted order"_test = [] {
        for (const Anchor& anchor : kAnchors) {
            const Form* form = nullptr;
            for (const Form& candidate : kForms) {
                if (std::string_view(candidate.code) == std::string_view(anchor.code)) {
                    form = &candidate;
                }
            }
            expect(form != nullptr) << anchor.code;
            if (form == nullptr) {
                continue;
            }
            const std::vector<std::uint8_t> codewordItems = bitsOf(anchor.codeword, form->n);
            const std::vector<std::uint8_t> infoItems     = bitsOf(anchor.info, form->k);

            const auto coded = runBlock<FecEncode>({{"code", std::string(anchor.code)}}, {record(infoItems)});
            expect(eq(coded.size(), 1UZ)) << anchor.code;
            if (coded.size() == 1UZ) {
                expect(std::ranges::equal(coded[0UZ].signal_values, codewordItems)) << anchor.code;
            }

            const auto out = runBlock<FecDecode>({{"code", std::string(anchor.code)}}, {record(codewordItems)});
            expect(eq(out.size(), 1UZ)) << anchor.code;
            if (out.size() == 1UZ) {
                expect(std::ranges::equal(out[0UZ].signal_values, infoItems)) << anchor.code;
                expect(eq(metaCount(out[0UZ], "corrected_errors"), gr::Size_t{0U})) << anchor.code;
                expect(eq(metaCount(out[0UZ], "uncorrectable_errors"), gr::Size_t{0U})) << anchor.code;
            }
        }
    };

    "the Reed-Solomon parity an independent implementation produces lands where the wire expects it"_test = [] {
        // The pinned parity of the shortened RS(24,12,13) code, for the information pattern the
        // kernel's own test uses. The adapter must place the same twelve symbols at the end of the
        // wire region, which fixes the symbol order the record carries.
        constexpr std::array<std::uint8_t, 12UZ> kParity{0x1AU, 0x3FU, 0x3AU, 0x3AU, 0x0DU, 0x03U, 0x05U, 0x21U, 0x1FU, 0x1DU, 0x17U, 0x19U};

        constexpr std::size_t     pad  = 39UZ;
        constexpr std::size_t     info = 63UZ - 12UZ - pad;
        std::vector<std::uint8_t> symbols(info);
        for (std::size_t i = 0UZ; i < info; ++i) {
            symbols[i] = static_cast<std::uint8_t>((7UZ * i + 5UZ) & 0x3FUZ);
        }

        const auto coded = runBlock<RsEncode>({{"roots", gr::Size_t{12U}}, {"pad", gr::Size_t{pad}}}, {record(symbols)});
        expect(eq(coded.size(), 1UZ));
        if (coded.size() != 1UZ) {
            return;
        }
        expect(eq(coded[0UZ].signal_values.size(), 63UZ - pad));
        expect(std::ranges::equal(std::span(coded[0UZ].signal_values).first(info), symbols)) << "the information leads the wire unchanged";
        expect(std::ranges::equal(std::span(coded[0UZ].signal_values).last(12UZ), std::span(kParity))) << "the parity follows it";
    };

    // Criterion 5: what the record already carried, and what the decode adds to it.
    "the decode adds its counts to the record's and carries every other key verbatim"_test = [] {
        const std::vector<std::uint8_t> info  = randomBits(2UZ * 12UZ);
        Record                          coded = encoded("golay24", info);
        flipBits(coded, {1UZ, 25UZ}); // one error in each of the two codewords

        coded.meta_information.resize(1UZ);
        coded.meta_information[0UZ]["corrected_errors"] = gr::Size_t{3U};
        coded.meta_information[0UZ]["provenance"]       = std::string("earlier stage");
        coded.meta_information[0UZ]["sample_start"]     = std::uint64_t{4096ULL};

        const auto out = runBlock<FecDecode>({{"code", std::string("golay24")}}, {coded});
        expect(eq(out.size(), 1UZ));
        if (out.size() != 1UZ) {
            return;
        }
        expect(eq(metaCount(out[0UZ], "corrected_errors"), gr::Size_t{5U})) << "three carried in plus the two this decode corrected";
        expect(eq(metaCount(out[0UZ], "uncorrectable_errors"), gr::Size_t{0U}));

        const auto& map = out[0UZ].meta_information[0UZ];
        const auto  who = map.find(gr::property_map::key_type("provenance"));
        expect(who != map.end());
        if (who != map.end()) {
            expect(eq(who->second.value_or(std::string{}), std::string("earlier stage")));
        }
        const auto at = map.find(gr::property_map::key_type("sample_start"));
        expect(at != map.end());
        if (at != map.end()) {
            expect(eq(at->second.value_or(std::uint64_t{0ULL}), std::uint64_t{4096ULL}));
        }
        expect(std::ranges::equal(out[0UZ].signal_values, info));
        expect(eq(out[0UZ].signal_names.size(), 1UZ)) << "the record's signal name follows it through";
    };

    "a record arriving without a metadata map gains one for the status keys"_test = [] {
        Record coded = encoded("hamming15", randomBits(11UZ));
        coded.meta_information.clear();
        const auto out = runBlock<FecDecode>({{"code", std::string("hamming15")}}, {coded});
        expect(eq(out.size(), 1UZ));
        if (out.size() == 1UZ) {
            expect(eq(out[0UZ].meta_information.size(), 1UZ));
            expect(eq(metaCount(out[0UZ], "corrected_errors"), gr::Size_t{0U}));
        }
    };

    // Criterion 6: a misaligned record is dropped, counted, and costs only itself.
    "a misaligned record is dropped and counted, and the record after it is processed"_test = [] {
        const std::vector<std::uint8_t> good = randomBits(2UZ * 12UZ);
        const auto                      out  = runBlock<FecEncode>({{"code", std::string("golay24")}},           //
                                  {record(randomBits(13UZ)), record(good), record(std::vector<std::uint8_t>{})}, //
                                  [](const FecEncode& block) {
                expect(eq(block.nRecordsRefused, std::uint64_t{2ULL})) << "the misaligned record and the empty one";
                expect(eq(block.nRecords, std::uint64_t{1ULL}));
                expect(eq(block.nCodewords, std::uint64_t{2ULL}));
            });
        expect(eq(out.size(), 1UZ)) << "only the aligned record was published";
        if (out.size() == 1UZ) {
            expect(eq(out[0UZ].signal_values.size(), 2UZ * 24UZ));
        }
    };

    "a decode refuses a record that is not a whole number of codewords"_test = [] {
        const Record coded     = encoded("golay24", randomBits(12UZ));
        Record       truncated = coded;
        truncated.signal_values.pop_back();

        const auto out = runBlock<FecDecode>({{"code", std::string("golay24")}}, {truncated, coded}, [](const FecDecode& block) {
            expect(eq(block.nRecordsRefused, std::uint64_t{1ULL}));
            expect(eq(block.nRecords, std::uint64_t{1ULL}));
        });
        expect(eq(out.size(), 1UZ));
    };

    "a Reed-Solomon decode refuses a record that is not a whole number of codewords"_test = [] {
        const std::vector<std::uint8_t> symbols = randomSymbols(63UZ - 12UZ);
        const auto                      coded   = runBlock<RsEncode>({{"roots", gr::Size_t{12U}}}, {record(symbols)});
        expect(eq(coded.size(), 1UZ));
        if (coded.size() != 1UZ) {
            return;
        }
        Record truncated = coded[0UZ];
        truncated.signal_values.pop_back();

        const auto out = runBlock<RsDecode>({{"roots", gr::Size_t{12U}}}, {truncated, coded[0UZ]}, [](const RsDecode& block) {
            expect(eq(block.nRecordsRefused, std::uint64_t{1ULL}));
            expect(eq(block.nRecords, std::uint64_t{1ULL}));
        });
        expect(eq(out.size(), 1UZ));
    };

    // Criterion 7: the shortening, and the word that violates it.
    "each Reed-Solomon code round-trips at a nonzero shortening"_test = [] {
        struct Shortened {
            gr::Size_t roots;
            gr::Size_t pad;
        };
        constexpr std::array<Shortened, 3UZ> kShortened{{{8U, 39U}, {12U, 39U}, {16U, 27U}}};

        for (const Shortened& code : kShortened) {
            const std::size_t               info    = 63UZ - static_cast<std::size_t>(code.roots) - static_cast<std::size_t>(code.pad);
            const std::size_t               wire    = 63UZ - static_cast<std::size_t>(code.pad);
            const std::vector<std::uint8_t> symbols = randomSymbols(2UZ * info);

            const auto coded = runBlock<RsEncode>({{"roots", code.roots}, {"pad", code.pad}}, {record(symbols)});
            expect(eq(coded.size(), 1UZ)) << code.roots;
            if (coded.size() != 1UZ) {
                continue;
            }
            expect(eq(coded[0UZ].signal_values.size(), 2UZ * wire)) << code.roots;

            const auto out = runBlock<RsDecode>({{"roots", code.roots}, {"pad", code.pad}}, {coded[0UZ]}, [](const RsDecode& block) {
                expect(eq(block.nUncorrectableCodewords, std::uint64_t{0ULL}));
                expect(eq(block.nPadCorrupted, std::uint64_t{0ULL}));
            });
            expect(eq(out.size(), 1UZ)) << code.roots;
            if (out.size() == 1UZ) {
                expect(std::ranges::equal(out[0UZ].signal_values, symbols)) << code.roots;
            }
        }
    };

    "a word whose correction lands in the padding is counted apart and refused"_test = [] {
        constexpr std::size_t pad   = 39UZ;
        constexpr std::size_t roots = 12UZ;

        // A codeword of the unshortened code carrying one nonzero symbol where the shortening says
        // there can be none. Its wire region is what a receiver would see, and putting the agreed
        // zeros back leaves a block one symbol away from a word the shortened code cannot contain.
        gr::fec::ReedSolomon6<roots>::Block full{};
        full[pad - 1UZ] = 0x2AU;
        for (std::size_t i = pad; i < 63UZ - roots; ++i) {
            full[i] = static_cast<std::uint8_t>((5UZ * i + 3UZ) & 0x3FUZ);
        }
        gr::fec::ReedSolomon6<roots>::encode(full, 0UZ);

        const std::vector<std::uint8_t> wire(full.begin() + static_cast<std::ptrdiff_t>(pad), full.end());
        const auto                      out = runBlock<RsDecode>({{"roots", gr::Size_t{roots}}, {"pad", gr::Size_t{pad}}}, {record(wire)}, [](const RsDecode& block) {
            expect(eq(block.nPadCorrupted, std::uint64_t{1ULL}));
            expect(eq(block.nUncorrectableCodewords, std::uint64_t{1ULL}));
            expect(eq(block.nCorrectedErrors, std::uint64_t{1ULL}));
        });
        expect(eq(out.size(), 1UZ)) << "the record still publishes";
        if (out.size() == 1UZ) {
            expect(eq(metaCount(out[0UZ], "uncorrectable_errors"), gr::Size_t{1U}));
            expect(eq(metaCount(out[0UZ], "corrected_errors"), gr::Size_t{1U}));
        }
    };

    // Criterion 8: encode, damage and decode in one graph, with the records staying in order.
    "an encode, a deterministic bit flipper and a decode compose in one graph"_test = [] {
        constexpr std::size_t                  records = 3UZ;
        constexpr std::size_t                  words   = 2UZ;
        std::vector<std::vector<std::uint8_t>> info(records);
        std::vector<Record>                    sources;
        sources.reserve(records);
        for (std::size_t r = 0UZ; r < records; ++r) {
            info[r] = randomBits(words * 12UZ);
            sources.push_back(record(info[r], {{"seq", static_cast<gr::Size_t>(r)}}));
        }

        gr::Graph flow;
        auto&     src    = flow.emplaceBlock<RecordSource>();
        src._records     = std::move(sources);
        auto& coder      = flow.emplaceBlock<FecEncode>({{"code", std::string("golay24")}});
        auto& noise      = flow.emplaceBlock<BitFlipper>();
        noise._positions = {1UZ, 26UZ}; // one bit in each of the two codewords a record carries
        auto& decoder    = flow.emplaceBlock<FecDecode>({{"code", std::string("golay24")}});
        auto& sink       = flow.emplaceBlock<RecordSink>();
        expect(flow.connect<"out", "in">(src, coder).has_value());
        expect(flow.connect<"out", "in">(coder, noise).has_value());
        expect(flow.connect<"out", "in">(noise, decoder).has_value());
        expect(flow.connect<"out", "in">(decoder, sink).has_value());

        std::vector<Record> out;
        runFlow(std::move(flow), [&] {
            expect(eq(coder.nRecords, std::uint64_t{records}));
            expect(eq(coder.nCodewords, std::uint64_t{records * words}));
            expect(eq(decoder.nRecords, std::uint64_t{records}));
            expect(eq(decoder.nCodewords, std::uint64_t{records * words}));
            expect(eq(decoder.nCorrectedErrors, std::uint64_t{records * words}));
            expect(eq(decoder.nUncorrectableCodewords, std::uint64_t{0ULL}));
            out = std::move(sink._records);
        });

        expect(eq(out.size(), records));
        if (out.size() != records) {
            return;
        }
        for (std::size_t r = 0UZ; r < records; ++r) {
            expect(std::ranges::equal(out[r].signal_values, info[r])) << "record" << r;
            expect(eq(metaCount(out[r], "seq"), static_cast<gr::Size_t>(r))) << "the records leave in the order they arrived";
            expect(eq(metaCount(out[r], "corrected_errors"), static_cast<gr::Size_t>(words))) << "record" << r;
            expect(eq(metaCount(out[r], "uncorrectable_errors"), gr::Size_t{0U})) << "record" << r;
        }
    };

    "a CCSDS profile round-trips over its whole surface, through the bursts interleaving exists for"_test = [] {
        struct Profile {
            const char* code;
            std::size_t e;
        };
        for (const Profile profile : {Profile{"ccsds_255_223", 16UZ}, Profile{"ccsds_255_239", 8UZ}}) {
            for (const char* basis : {"conventional", "dual"}) {
                for (const gr::Size_t depth : {1U, 2U, 3U, 4U, 5U, 8U}) {
                    // every allowed depth runs; the shortened arm runs at the depths interleaving
                    // interacts with the pad arithmetic, keeping the binary inside its budget
                    const bool padded = depth == 1U || depth == 5U || depth == 8U;
                    for (const gr::Size_t padding : padded ? std::initializer_list<gr::Size_t>{0U, 100U} : std::initializer_list<gr::Size_t>{0U}) {
                        const std::size_t      info = 255UZ - 2UZ * profile.e - padding;
                        const gr::property_map settings{{"code", std::string(profile.code)}, {"basis", std::string(basis)}, {"interleave", depth}, {"pad", padding}};

                        std::vector<std::uint8_t> symbols(info * depth);
                        for (std::uint8_t& s : symbols) {
                            s = static_cast<std::uint8_t>(next() & 0xFFULL);
                        }

                        // encode, burst and decode in one graph: a burst of E*I consecutive symbols in
                        // the interleaved stream lands E errors on every codeword — the burst the
                        // interleaver exists to spread
                        gr::Graph flow;
                        auto&     src = flow.emplaceBlock<RecordSource>();
                        src._records  = {record(symbols)};
                        auto& coder   = flow.emplaceBlock<RsEncode>(settings);
                        auto& burst   = flow.emplaceBlock<BitFlipper>();
                        for (std::size_t j = 0UZ; j < profile.e * depth; ++j) {
                            burst._positions.push_back(5UZ + j);
                        }
                        auto& decoder = flow.emplaceBlock<RsDecode>(settings);
                        auto& sink    = flow.emplaceBlock<RecordSink>();
                        expect(flow.connect<"out", "in">(src, coder).has_value());
                        expect(flow.connect<"out", "in">(coder, burst).has_value());
                        expect(flow.connect<"out", "in">(burst, decoder).has_value());
                        expect(flow.connect<"out", "in">(decoder, sink).has_value());

                        std::vector<Record> out;
                        runFlow(std::move(flow), [&] {
                            expect(eq(coder.nCodewords, std::uint64_t{depth})) << "one codeblock is I codewords";
                            expect(eq(decoder.nCorrectedErrors, std::uint64_t{profile.e * depth})) << "every codeword corrected its radius";
                            expect(eq(decoder.nUncorrectableCodewords, std::uint64_t{0ULL}));
                            out = std::move(sink._records);
                        });
                        expect(eq(out.size(), 1UZ)) << profile.code;
                        if (!out.empty()) {
                            expect(std::ranges::equal(out[0UZ].signal_values, symbols)) << std::format("{} {} I={} pad={}", profile.code, basis, depth, padding);
                            expect(eq(metaCount(out[0UZ], "corrected_errors"), static_cast<gr::Size_t>(profile.e * depth)));
                            expect(eq(metaCount(out[0UZ], "uncorrectable_errors"), gr::Size_t{0U}));
                        }
                    }
                }
            }
        }
    };

    "interleave depth 1 is the setting absent, byte for byte"_test = [] {
        const std::vector<std::uint8_t> symbols = randomSymbols(2UZ * 55UZ); // two GF(64) information words at roots 8

        const auto absent  = runBlock<RsEncode>({{"roots", gr::Size_t{8U}}}, {record(symbols)});
        const auto depthed = runBlock<RsEncode>({{"roots", gr::Size_t{8U}}, {"interleave", gr::Size_t{1U}}}, {record(symbols)});
        expect(eq(absent.size(), 1UZ));
        expect(eq(depthed.size(), 1UZ));
        if (!absent.empty() && !depthed.empty()) {
            expect(std::ranges::equal(absent[0UZ].signal_values, depthed[0UZ].signal_values)) << "the same code path is the identity at depth 1";
        }
    };

    "the profile's refusals fire by name"_test = [] {
        expect(throws([] { std::ignore = make<RsEncode>({{"code", std::string("ccsds_255_223")}}); })) << "basis has no default under a profile: a wrong choice decodes nothing";
        expect(throws([] { std::ignore = make<RsEncode>({{"code", std::string("ccsds_255_223")}, {"basis", std::string("dual")}, {"interleave", gr::Size_t{6U}}}); })) << "4.3.5.1 has no depth 6";
        expect(throws([] { std::ignore = make<RsEncode>({{"code", std::string("ccsds_255_223")}, {"basis", std::string("dual")}, {"interleave", gr::Size_t{7U}}}); })) << "nor 7";
        expect(nothrow([] { std::ignore = make<RsEncode>({{"code", std::string("ccsds_255_223")}, {"basis", std::string("dual")}, {"interleave", gr::Size_t{8U}}}); })) << "8 is the set's last member";
        expect(throws([] { std::ignore = make<RsEncode>({{"code", std::string("ccsds_255_223")}, {"basis", std::string("dual")}, {"roots", gr::Size_t{16U}}}); })) << "a profile's parity count is not negotiable";
        expect(nothrow([] { std::ignore = make<RsEncode>({{"code", std::string("ccsds_255_223")}, {"basis", std::string("dual")}, {"roots", gr::Size_t{32U}}}); })) << "agreement is not a conflict";
        expect(throws([] { std::ignore = make<RsEncode>({{"code", std::string("rs_experimental")}}); })) << "there is no free-form code tuple";
        expect(throws([] { std::ignore = make<RsEncode>({{"roots", gr::Size_t{8U}}, {"basis", std::string("dual")}}); })) << "the GF(64) family has no basis convention";
        expect(throws([] { std::ignore = make<RsDecode>({{"roots", gr::Size_t{8U}}, {"interleave", gr::Size_t{9U}}}); })) << "past this document's own bound";
        expect(nothrow([] { std::ignore = make<RsDecode>({{"roots", gr::Size_t{8U}}, {"interleave", gr::Size_t{7U}}}); })) << "the GF(64) family takes any depth to 8";
        expect(throws([] { std::ignore = make<RsDecode>({{"code", std::string("ccsds_255_239")}, {"basis", std::string("conventional")}, {"pad", gr::Size_t{239U}}}); })) << "a shortening that leaves no information, under the 255-symbol block";
        expect(nothrow([] { std::ignore = make<RsDecode>({{"code", std::string("ccsds_255_239")}, {"basis", std::string("conventional")}, {"pad", gr::Size_t{238U}}}); })) << "the last one that leaves a symbol";
    };

    "the two bases are two wires"_test = [] {
        std::vector<std::uint8_t> symbols(223UZ);
        for (std::uint8_t& s : symbols) {
            s = static_cast<std::uint8_t>(next() & 0xFFULL);
        }
        const gr::property_map conventional{{"code", std::string("ccsds_255_223")}, {"basis", std::string("conventional")}};
        const gr::property_map dual{{"code", std::string("ccsds_255_223")}, {"basis", std::string("dual")}};

        const auto plain   = runBlock<RsEncode>(conventional, {record(symbols)});
        const auto recoded = runBlock<RsEncode>(dual, {record(symbols)});
        expect(eq(plain.size(), 1UZ));
        expect(eq(recoded.size(), 1UZ));
        if (plain.empty() || recoded.empty()) {
            return;
        }
        expect(that % !std::ranges::equal(plain[0UZ].signal_values, recoded[0UZ].signal_values)) << "the recoding changes the wire";

        // a codeword of one basis read under the other is not this code's word
        const auto crossed = runBlock<RsDecode>(conventional, {recoded[0UZ]});
        expect(eq(crossed.size(), 1UZ));
        if (!crossed.empty()) {
            expect(that % metaCount(crossed[0UZ], "uncorrectable_errors") > 0U) << "a wrong basis decodes nothing, which is why the setting has no default";
        }
    };

    // The GF(16) BCH(15,k) family's three new `code` values, over the same round-trip, in-radius correction,
    // past-radius refusal, metadata accumulation and misalignment criteria the other binary forms above are held to.
    "the length-15 BCH family round-trips, corrects to its radius, and refuses past it"_test = [] {
        struct Bch15Form {
            const char*   code;
            std::size_t   k;
            unsigned      t;
            std::uint16_t generator;
            bool          pastRadiusRefused; //!< what the code does with this test's own weight-(t+1) pattern
        };
        // (15,11,3) is perfect, so no word is ever past its radius; the other two refuse or miscorrect by the
        // pattern, and which one this test's pattern falls under is settled from the generator below.
        constexpr std::array<Bch15Form, 3UZ> kBch15Forms{{
            {"bch15_11", 11UZ, 1U, 0x0013U, false},
            {"bch15_7", 7UZ, 2U, 0x01D1U, false},
            {"bch15_5", 5UZ, 3U, 0x0537U, true},
        }};

        for (const Bch15Form& form : kBch15Forms) {
            // criterion 1: a round trip reproduces the information exactly, with nothing corrected.
            const std::vector<std::uint8_t> info  = randomBits(3UZ * form.k);
            const Record                    coded = encoded(form.code, info);
            expect(eq(coded.signal_values.size(), 3UZ * 15UZ)) << form.code;

            const auto clean = runBlock<FecDecode>({{"code", std::string(form.code)}}, {coded}, [](const FecDecode& block) {
                expect(eq(block.nCorrectedErrors, std::uint64_t{0ULL}));
                expect(eq(block.nUncorrectableCodewords, std::uint64_t{0ULL}));
            });
            expect(eq(clean.size(), 1UZ)) << form.code;
            if (clean.size() == 1UZ) {
                expect(std::ranges::equal(clean[0UZ].signal_values, info)) << form.code;
            }

            // criterion 2: t errors per codeword are corrected and counted exactly.
            Record damaged = coded;
            for (std::size_t w = 0UZ; w < 3UZ; ++w) {
                flipBits(damaged, errorPositions(w * 15UZ, form.t));
            }
            const gr::Size_t injected = 3U * form.t;
            const auto       repaired = runBlock<FecDecode>({{"code", std::string(form.code)}}, {damaged}, [injected](const FecDecode& block) {
                expect(eq(block.nCorrectedErrors, static_cast<std::uint64_t>(injected)));
                expect(eq(block.nUncorrectableCodewords, std::uint64_t{0ULL}));
            });
            expect(eq(repaired.size(), 1UZ)) << form.code;
            if (repaired.size() == 1UZ) {
                expect(std::ranges::equal(repaired[0UZ].signal_values, info)) << form.code;
                expect(eq(metaCount(repaired[0UZ], "corrected_errors"), injected)) << form.code;
            }

            // past the radius the record still publishes. Whether that specific codeword and error pattern is
            // corrected to a neighbor or refused is a property of the code, so the expectation is computed from the
            // generator — the codeword set built in full, and the received word measured against all of it.
            Record beyond = coded;
            flipBits(beyond, errorPositions(0UZ, form.t + 1U));
            std::uint64_t firstWord = 0ULL; // the same MSB-first item-to-word mapping the adapter itself uses
            for (std::size_t i = 0UZ; i < 15UZ; ++i) {
                firstWord = (firstWord << 1U) | (beyond.signal_values[i] & 1U);
            }
            const std::vector<std::uint16_t> codewords = bch15Codewords(form.generator, form.k);
            const bool                       reachable = withinRadius(codewords, static_cast<std::uint16_t>(firstWord), form.t);
            expect(eq(!reachable, form.pastRadiusRefused)) << form.code << ": the codeword set says whether this pattern is refused or miscorrected";
            const gr::Size_t expectedUncorrectable = reachable ? gr::Size_t{0U} : gr::Size_t{1U};
            const auto       past                  = runBlock<FecDecode>({{"code", std::string(form.code)}}, {beyond}, [expectedUncorrectable](const FecDecode& block) {
                expect(eq(block.nUncorrectableCodewords, static_cast<std::uint64_t>(expectedUncorrectable)));
                expect(eq(block.nRecords, std::uint64_t{1ULL})) << "an uncorrectable codeword is still published";
            });
            expect(eq(past.size(), 1UZ)) << form.code;
            if (past.size() == 1UZ) {
                expect(eq(past[0UZ].signal_values.size(), 3UZ * form.k)) << "the information bits ride whatever the verdict was";
                expect(eq(metaCount(past[0UZ], "uncorrectable_errors"), expectedUncorrectable)) << form.code;
            }
        }
    };

    "a misaligned bch15 record is dropped and counted, and the record after it is processed"_test = [] {
        const std::vector<std::uint8_t> good = randomBits(2UZ * 11UZ);
        const auto                      out  = runBlock<FecEncode>({{"code", std::string("bch15_11")}},         //
                                  {record(randomBits(4UZ)), record(good), record(std::vector<std::uint8_t>{})}, //
                                  [](const FecEncode& block) {
                expect(eq(block.nRecordsRefused, std::uint64_t{2ULL})) << "the misaligned record and the empty one";
                expect(eq(block.nRecords, std::uint64_t{1ULL}));
                expect(eq(block.nCodewords, std::uint64_t{2ULL}));
            });
        expect(eq(out.size(), 1UZ)) << "only the aligned record was published";
        if (out.size() == 1UZ) {
            expect(eq(out[0UZ].signal_values.size(), 2UZ * 15UZ));
        }
    };

    "a cyclic BCH(15,11) codeword handed to the landed Hamming decoder comes back wrong, and nothing says so"_test = [] {
        constexpr std::size_t     kWords = 8UZ;
        std::vector<std::uint8_t> info;
        for (std::uint64_t word = 1ULL; word <= kWords; ++word) {
            const std::vector<std::uint8_t> bits = bitsOf(word, 11UZ);
            info.insert(info.end(), bits.begin(), bits.end());
        }

        const Record coded = encoded("bch15_11", info);
        expect(eq(coded.signal_values.size(), kWords * 15UZ));

        // both codes are Hamming(15,11,3) and share 128 of their 2048 codewords, so the wrong decoder finds a
        // nearest codeword every time and reports success: the trap is that there is no failure to observe
        const auto crossed = runBlock<FecDecode>({{"code", std::string("hamming15")}}, {coded}, [](const FecDecode& block) { expect(eq(block.nUncorrectableCodewords, std::uint64_t{0ULL})) << "a perfect code cannot refuse"; });
        expect(eq(crossed.size(), 1UZ));
        if (crossed.size() != 1UZ) {
            return;
        }
        expect(eq(crossed[0UZ].signal_values.size(), kWords * 11UZ));
        std::size_t wrong = 0UZ;
        for (std::size_t word = 0UZ; word < kWords; ++word) {
            const auto at = static_cast<std::ptrdiff_t>(word * 11UZ);
            if (!std::equal(info.begin() + at, info.begin() + at + 11, crossed[0UZ].signal_values.begin() + at)) {
                ++wrong;
            }
        }
        expect(that % (wrong > 0UZ)) << "the two (15,11,3) codes are different codes";
        expect(eq(metaCount(crossed[0UZ], "uncorrectable_errors"), gr::Size_t{0U})) << "and the record carries no count that would have warned anybody";
    };

    "the bit-order pin: the systematic codeword of information word one is the generator, built item by item"_test = [] {
        struct Bch15Anchor {
            const char*   code;
            std::uint64_t generator;
            std::size_t   k;
        };
        constexpr std::array<Bch15Anchor, 3UZ> kBch15Anchors{{
            {"bch15_11", 0x0013ULL, 11UZ}, // x^4 + x + 1
            {"bch15_7", 0x01D1ULL, 7UZ},   // x^8 + x^7 + x^6 + x^4 + 1
            {"bch15_5", 0x0537ULL, 5UZ},   // x^10 + x^8 + x^5 + x^4 + x^2 + x + 1
        }};

        for (const Bch15Anchor& anchor : kBch15Anchors) {
            const std::vector<std::uint8_t> codewordItems = bitsOf(anchor.generator, 15UZ);
            const std::vector<std::uint8_t> infoItems     = bitsOf(1ULL, anchor.k);

            const auto coded = runBlock<FecEncode>({{"code", std::string(anchor.code)}}, {record(infoItems)});
            expect(eq(coded.size(), 1UZ)) << anchor.code;
            if (coded.size() == 1UZ) {
                expect(std::ranges::equal(coded[0UZ].signal_values, codewordItems)) << anchor.code;
            }

            const auto out = runBlock<FecDecode>({{"code", std::string(anchor.code)}}, {record(codewordItems)});
            expect(eq(out.size(), 1UZ)) << anchor.code;
            if (out.size() == 1UZ) {
                expect(std::ranges::equal(out[0UZ].signal_values, infoItems)) << anchor.code;
                expect(eq(metaCount(out[0UZ], "corrected_errors"), gr::Size_t{0U})) << anchor.code;
                expect(eq(metaCount(out[0UZ], "uncorrectable_errors"), gr::Size_t{0U})) << anchor.code;
            }
        }
    };

    return 0;
}
