add_ut_test(qa_Agc)
target_link_libraries(qa_Agc PRIVATE gr-analog gr-testing)
add_ut_test(qa_FmEmphasis)
target_link_libraries(qa_FmEmphasis PRIVATE gr-analog gr-testing)
add_ut_test(qa_QuadratureDemod)
target_link_libraries(qa_QuadratureDemod PRIVATE gr-analog gr-testing)
add_ut_test(qa_PowerSquelch)
target_link_libraries(qa_PowerSquelch PRIVATE gr-analog gr-testing)
add_ut_test(qa_CtcssSquelch)
target_link_libraries(qa_CtcssSquelch PRIVATE gr-analog gr-testing)
add_ut_test(qa_SimpleSquelch)
target_link_libraries(qa_SimpleSquelch PRIVATE gr-analog gr-testing)
add_ut_test(qa_PowerMeter)
target_link_libraries(qa_PowerMeter PRIVATE gr-analog gr-testing)
add_ut_test(qa_NoiseBlanker)
target_link_libraries(qa_NoiseBlanker PRIVATE gr-analog gr-testing)

add_ut_test(qa_HardLimiter)
target_link_libraries(qa_HardLimiter PRIVATE gr-analog gr-testing)
