add_ut_test(qa_Pll)
target_link_libraries(qa_Pll PRIVATE gr-sync gr-testing)
add_ut_test(qa_CostasLoop)
target_link_libraries(qa_CostasLoop PRIVATE gr-sync gr-testing)
add_ut_test(qa_FllBandEdge)
target_link_libraries(qa_FllBandEdge PRIVATE gr-sync gr-testing)
add_ut_test(qa_SymbolSync)
target_link_libraries(qa_SymbolSync PRIVATE gr-sync gr-testing)
add_ut_test(qa_PreambleTiming)
target_link_libraries(qa_PreambleTiming PRIVATE gr-sync gr-testing)
