add_ut_test(qa_Awgn)
target_link_libraries(qa_Awgn PRIVATE gr-channel)
add_ut_test(qa_CarrierImpairments)
target_link_libraries(qa_CarrierImpairments PRIVATE gr-channel)
add_ut_test(qa_ChannelConverter)
target_link_libraries(qa_ChannelConverter PRIVATE gr-channel)
add_ut_test(qa_DopplerShift)
target_link_libraries(qa_DopplerShift PRIVATE gr-channel gr-testing)
add_ut_test(qa_RangeDelay)
target_link_libraries(qa_RangeDelay PRIVATE gr-channel)
add_ut_test(qa_TrajectoryPass)
target_link_libraries(qa_TrajectoryPass PRIVATE gr-channel)
add_ut_test(qa_Fading)
target_link_libraries(qa_Fading PRIVATE gr-channel)
